# Generated by Django 5.1.7 on 2026-03-26 00:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0004_applicationconfiguration_barcode_asn_prefix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_s3_access_key_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sets the S3 access key ID",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_s3_addressing_style",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Sets the S3 addressing style",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_s3_bucket",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sets the S3 bucket for documents",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_s3_custom_domain",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sets the S3 custom domain",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_s3_default_acl",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sets the S3 default ACL",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_s3_endpoint_url",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Sets the S3 endpoint URL",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_s3_querystring_auth",
            field=models.BooleanField(
                null=True,
                verbose_name="Sets whether S3 querystring auth is enabled",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_s3_region_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sets the S3 region",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_s3_secret_access_key",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sets the S3 secret access key",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_s3_url_protocol",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Sets the S3 URL protocol",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_s3_use_ssl",
            field=models.BooleanField(
                null=True,
                verbose_name="Sets whether S3 uses SSL",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_storage_prefix",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sets the document storage prefix",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="documents_storage_type",
            field=models.CharField(
                blank=True,
                choices=[("local", "local"), ("s3", "s3")],
                max_length=16,
                null=True,
                verbose_name="Sets the document storage backend",
            ),
        ),
    ]
