# Generated by Django 5.2.12 on 2026-03-28 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0007_optimize_integer_field_sizes"),
        ("paperless", "1009_applicationconfiguration_automatic_backup_jobs"),
    ]

    operations = []
