# Generated by Django 5.2.12 on 2026-03-28 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1077_alter_paperlesstask_task_name"),
        ("documents", "1077_merge_20260305_0750"),
    ]

    operations = []
