# Generated by Django 5.2.12 on 2026-03-28 12:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1078_merge_20260328_0832"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="custom_fields",
            field=models.ManyToManyField(
                blank=True,
                related_name="document_types",
                to="documents.customfield",
                verbose_name="custom fields",
            ),
        ),
    ]
