# Generated by Django 5.2.12 on 2026-03-30 13:57

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1081_document_retention_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttype",
            name="retention_period_years",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional retention period in years. Documents of this type cannot be deleted before the calculated date.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="retention period in years",
            ),
        ),
        migrations.AlterField(
            model_name="paperlesstask",
            name="task_name",
            field=models.CharField(
                choices=[
                    ("consume_file", "Consume File"),
                    ("import_file", "Import File"),
                    ("train_classifier", "Train Classifier"),
                    ("check_sanity", "Check Sanity"),
                    ("index_optimize", "Index Optimize"),
                    ("llmindex_update", "LLM Index Update"),
                    ("export_s3_storage", "Export S3 Storage"),
                    ("import_s3_storage", "Import S3 Storage"),
                    ("scheduled_backup_s3_storage", "Scheduled Backup S3 Storage"),
                ],
                help_text="Name of the task that was run",
                max_length=255,
                null=True,
                verbose_name="Task Name",
            ),
        ),
        migrations.AlterField(
            model_name="savedview",
            name="group_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("storagePath", "Storage path"),
                    ("correspondent", "Correspondent"),
                    ("documentType", "Document type"),
                    ("createdYear", "Created year"),
                    ("createdMonth", "Created month"),
                ],
                max_length=128,
                null=True,
                verbose_name="View group by",
            ),
        ),
    ]
