# Generated by Django 5.2.12 on 2026-04-04 10:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1083_workflow_manual_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrun",
            name="current_step_order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="current step order",
            ),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="error",
            field=models.TextField(blank=True, default="", verbose_name="error"),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="finished_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="date finished",
            ),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="message",
            field=models.TextField(blank=True, default="", verbose_name="message"),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="result_data",
            field=models.JSONField(blank=True, null=True, verbose_name="result data"),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="started_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="date started",
            ),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="started_workflow_runs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="started by",
            ),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="success",
                max_length=16,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowRunStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="order")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date started",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="date finished",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="message"),
                ),
                (
                    "error",
                    models.TextField(blank=True, default="", verbose_name="error"),
                ),
                (
                    "request_payload",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="request payload",
                    ),
                ),
                (
                    "response_payload",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="response payload",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="run_steps",
                        to="documents.workflowaction",
                        verbose_name="workflow action",
                    ),
                ),
                (
                    "workflow_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="documents.workflowrun",
                        verbose_name="workflow run",
                    ),
                ),
            ],
            options={
                "verbose_name": "workflow run step",
                "verbose_name_plural": "workflow run steps",
                "ordering": ("order", "pk"),
            },
        ),
    ]
